### PR TITLE
quick start

### PR DESCRIPTION
**Pull request by melbit-paulcameron**
* made a start on the crane area
* included map.png and intermediate files (removed .gitignore restrictions) to allow rapid start for other mappers to grab and go with the map.
* doco updates

* don't feel obliged to approve, I'll keep chipping away at my part in time. Just adding a PR to let you know stuff is happening :-D

### CODE REVIEW

**Comment by anoshi** [comment]
Oh the things you can achieve when logged in as the right user :-|

**Comment by david-wm-sanders** [comment]
requested PR adjustments:
* fix README issue in `## About`
* re-add intermediate files to .gitignore (and then clean these intermediates from the branch) but leave terrain5_*.png and map.png included (then we can make a gif at the end to show map development 😆)

i will then merge this into master so that others can see your excellent progress and be inspired :P

**Comment by anoshi** [comment]
I think that's got it now, thanks :-)

**Comment by david-wm-sanders** [comment]
github configured to delete branch on merge - will need to repush your branch if you continue work in it 😄

👍 i have adjusted the readme so it shows the map.png in about now

**Pull request merged**
